image: node:lts-alpine

variables:
    PORT: 4029

stages:
    - deploy

deploy to test:
    stage: deploy
    tags:
        - urt-web-app1-for-web-gr
    variables:
        HOST: $TEST_HOST
        NODE_ENV: test
        DB_TYPE: fs
        DOCKER: "true"
        FS_DIRECTORY: "/files/"
        DISABLE_EMAIL_VERIFICATION: "true"
        DISABLE_STORAGE: "true"
        MONGODB_URL: $TEST_MONGO_URI
        REMOTE_URL: http://$TEST_HOST:$PORT
        PASSWORD_ACCESS: ca9cfc3070a69fcca8980c16064bfbd1fa118adc64ac1496ea8beca8c68dcecd
        PASSWORD_REFRESH: a8f90dc1cdb5333a4bd6ba92462c346b6f79708e9d245579a366a912a3627bc1
        PASSWORD_COOKIE: 30bbf48416e35af8902faf239aecf6b367262899352fed75976694d18c042cf2
    before_script:
        - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    script:
        - docker-compose up -d --no-deps --build
    after_script:
        - docker system prune -af
        - docker stats --no-stream
        - docker logout $CI_REGISTRY
    only:
        - test

deploy to prod:
    stage: deploy
    tags:
        - uhp-web-app1-for-web-gr
    variables:
        REMOTE_URL: http://$HOST:$PORT # need to set to prod url
        NODE_ENV: production
        DB_TYPE: fs
        DOCKER: "true"
        FS_DIRECTORY: "/files/"
        DISABLE_EMAIL_VERIFICATION: "true"
        DISABLE_STORAGE: "true"
        MONGODB_URL: $MONGO_URI
        PASSWORD_ACCESS: $DAM_PASSWORD_ACCESS
        PASSWORD_REFRESH: $DAM_PASSWORD_REFRESH
        PASSWORD_COOKIE: $DAM_PASSWORD_COOKIE
    before_script:
        - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    script:
        - docker-compose up -d --no-deps --build
    after_script:
        - docker system prune -af
        - docker stats --no-stream
        - docker logout $CI_REGISTRY
    only:
        - master
