version: '2'

services:
  dam:
    container_name: dam
    build:
      context: .
      args: 
        - PROXY
        - NO_PROXY
        - NPM_REGISTRY
    environment:
      - HOST
      - NODE_ENV
      - DB_TYPE
      - DOCKER
      - FS_DIRECTORY
      - DISABLE_EMAIL_VERIFICATION
      - DISABLE_STORAGE
      - MONGODB_URL
      - REMOTE_URL
      - PASSWORD_ACCESS
      - PASSWORD_REFRESH
      - PASSWORD_COOKIE
    ports: 
      - $PORT:8080
    volumes:
      - ./files/:$FS_DIRECTORY
    mem_limit: 1g
    logging: 
      driver: 'fluentd'
      options: 
        fluentd-async-connect: "true"
        fluentd-address: $HOST:24224
        tag: docker.dam
    network_mode: bridge
    restart: always