version: '2'

services:
  dam:
    container_name: dam
    restart: always
    build: 
      context: .
      args: 
        - PROXY
        - NO_PROXY
        - NPM_REGISTRY
    environment: 
      - NODE_ENV
      - DB_TYPE
      - DOCKER
      - DISABLE_EMAIL_VERIFICATION
      - DISABLE_STORAGE
      - MONGODB_URL
      - REMOTE_URL
      - PASSWORD_ACCESS
      - PASSWORD_REFRESH
      - PASSWORD_COOKIE
    ports: 
      - $PORT:8080